### ISSUE TITLE
The extended hotbar overlap on xpbar

### ISSUE THREAD

**Issue by a08381** [DemonWav/ExtendedHotbar#1]
this mod is great!

but this looks a little awful...

![qq 20170804161941](https://user-images.githubusercontent.com/2505002/28960573-cdec611e-7931-11e7-84c0-6822dc0f0fbf.png)

can u fix this?

**Comment by a08381** [comment]
it seens mixin worked correctly?

[http://paste.ubuntu.com/25238590/]

**Comment by DemonWav** [comment]
Can you list out all the mods you're using please?

**Comment by DemonWav** [comment]
What would be really helpful is the whole log. Open LiteLoader panel, press F3, and click the upload button, and paste the log URL here.

**Comment by a08381** [comment]
Got 400 when upload my log.
I paste it on here.
http://paste.ubuntu.com/25260696/

**Comment by Mumfrey** [comment]
You got a 400 code because you're not using a legal copy of the game.

**Comment by a08381** [comment]
aha... I seldom login with mojang account because of netease :P
netease got the agent from microsoft, and he use his own online mode :(
here is log on liteloader: http://logs.liteloader.com/view/9fxkTmj

**Comment by DemonWav** [comment]
Same issue as #4.
