### ISSUE TITLE
Pick Block(Middle click) moves items from other hotbars

### ISSUE THREAD

**Issue by SHsuperCM** [DemonWav/ExtendedHotbar#3]
When you pick block with middle click by default it should just switch selected slot to the item's if it exists in the hotbar like the vanilla hotbar, instead of switching the selected slot to another hotbar, it takes the item from the hotbar and puts it in the current hotbar...

**Comment by DemonWav** [comment]
This is default behavior if you think about what ExtendedHotbar is really doing - just displaying the bottom row of your inventory above your current hotbar. If you were to place an item in another slot in your inventory above the bottom row, it would do the same thing, it would just look differently.

However, I see what you mean in that this should probably be a special case and it should behave like a hotbar. In this case, it should probably swap both rows and select the block that was clicked.
