### ISSUE TITLE
extended bar behind regular HUD

### ISSUE THREAD

**Issue by YAsvpp** [DemonWav/ExtendedHotbar#4]
hello i have a problem with the mod (using minecraft 1.12.1) as I said in the title, here's what it does : 
![2017-08-28_16 30 43](https://user-images.githubusercontent.com/31411795/29778212-de920204-8c0e-11e7-855a-a9b7b02597fe.png)

i also pasted my logs : 
http://logs.liteloader.com/view/J6GgQ8T

and finally i am using these followings mods : 

note block display 1.3.6
Optifine 1.12.1 HD U C5
Voxel map 1.7.0
Inventory Tweaks 1.63+108.6ff67c4
fullscreen windowed 1.6.0
Forge 1.12.1-14.22.0.2460
liteloader 1.12.1-00

I hope that all the infos i have given will be useful

**Comment by 112madgamer** [comment]
This is a issue with forge. The mod works fine without it

**Comment by DemonWav** [comment]
Fixed in ef76e96.
