### ISSUE TITLE
[Question / Feature request] Is there a way to invert the shift+key behavior?

### ISSUE THREAD

**Issue by Lion4K** [DemonWav/ExtendedHotbar#6]
Like, I've mapped the key to be TAB and I noticed that shift+tab only swaps the selected item.
I wanted this to be the default behavior and shift+tab swaps the whole hotbar.

Is it possible to be made?
Sorry if this is a bad place to ask.

**Comment by DemonWav** [comment]
Yeah that should be doable pretty easily.

**Comment by Lion4K** [comment]
Thanks!!!

**Comment by DemonWav** [comment]
I forgot about this, sorry. I'll see if I can go ahead and implement this option soon.
